- name: Launching Master instance
  ec2_instance:
         region: "{{ region_name }}"
         image_id: "{{ image_id }}" 
         instance_type: "{{ instance_type }}"
         vpc_subnet_id: "{{ subnet_id }}"
         security_group: "{{ security_group }}"
         key_name: "{{ key_name }}"
         name: Kube_Master
         state: present
         aws_access_key: "{{ access_key }}"
         aws_secret_key: "{{ secret_key }}"
  register: x


- name: Launching Slave1 instance
  ec2_instance:
         region: "{{ region_name }}"
         image_id: "{{ image_id }}" 
         instance_type: "{{ instance_type }}"
         vpc_subnet_id: "{{ subnet_id }}"
         security_group: "{{ security_group }}"
         key_name: "{{ key_name }}"
         name: Kube_Slave1
         state: present
         aws_access_key: "{{ access_key }}"
         aws_secret_key: "{{ secret_key }}"
  register: y

- name: Launching Slave2 instance
  ec2_instance:
         region: "{{ region_name }}"
         image_id: "{{ image_id }}" 
         instance_type: "{{ instance_type }}"
         vpc_subnet_id: "{{ subnet_id }}"
         security_group: "{{ security_group }}"
         name: Kube_Slave2
         state: present
         aws_access_key: "{{ access_key }}"
         aws_secret_key: "{{ secret_key }}"
  register: z


- name: Updating Inventory
  blockinfile:
               path: /root/ip.txt
               block: |
                   [Master]
                   {{ x.instances[0].public_ip_address }} ansible_user=ec2-user 

                   [Slaves]     
                   {{ y.instances[0].public_ip_address }} ansible_user=ec2-user 
                   {{ z.instances[0].public_ip_address }} ansible_user=ec2-user 
